install: code.py
	cp code.py /media/ccaroon/CIRCUITPY

install_twinkle: twinkle.py code.py
	cp twinkle.py code.py /media/ccaroon/CIRCUITPY

install_temp: thermo.py code.py
	cp thermo.py code.py /media/ccaroon/CIRCUITPY

win_install: code.py
	cp code.py d:/

term:
	sudo screen /dev/ttyACM0 115200
