include ../../../Ports.mk
include ../../../FileMgmt.mk

noop:
	@echo "Test Tube Application"

BOOT = ../../../boots/esp8266.pyc
APP  = main.pyc
LIBS = ../../../lib/chronos.pyc ../../../lib/wifi.pyc

include ../App.mk
