include ../../../Ports.mk
include ../../../FileMgmt.mk

noop:
	@echo "Test Tube Application"

BOOT = ../../../boots/esp8266.pyc
APP  = main.pyc
LIBS = ../../../lib/blynklib.mpy ../../../lib/chronos.mpy ../../../lib/wifi.mpy

include ../App.mk
